[window]
decorations = "None"
opacity = 0.95
padding = { x = 10, y = 10 }
startup_mode = "Maximized"

[scrolling]
history = 100000

[font]
normal = { family = "Comic Code Ligatures", style = "Regular" }
bold = { family = "Comic Code Ligatures", style = "Regular" }
italic = { family = "Comic Code Ligatures", style = "Italic" }
bold_italic = { family = "Comic Code Ligatures", style = "Italic" }

# Default colors
[colors.primary]
background = '#0A0E14'
foreground = '#d9e0ee'

# Normal colors
[colors.normal]
black   = '#272734'
red     = '#ec6a88'
green   = '#3FDAA4'
yellow  = '#e1c697'
blue    = '#78a9ff'
magenta = '#be95ff'
cyan    = '#09deda'
white   = '#d9e0ee'

# Bright colors
[colors.bright]
black   = '#67698a'
red     = '#ff7eb6'
green   = '#08bdba'
yellow  = '#e8d4b0'
blue    = '#3fc6de'
magenta = '#936fdc'
cyan    = '#6be6e6'
white   = '#ffffff'

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }

[keyboard]
bindings = [
  { key = "[", mods = "Control", action = "ToggleViMode" },
  { key = "V", mods = "Control", mode = "~Vi", action = "Paste" },
  { key = "Enter", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },
  { key = ")", mods = "Control|Shift", action = "ResetFontSize" },
]
