[window]
decorations = "None"
opacity = 0.95
padding = { x = 10, y = 10 }
startup_mode = "Maximized"

[scrolling]
history = 100000

[font]
normal = { family = "Comic Code Ligatures", style = "Regular" }
bold = { family = "Comic Code Ligatures", style = "Regular" }
italic = { family = "Comic Code Ligatures", style = "Italic" }
bold_italic = { family = "Comic Code Ligatures", style = "Italic" }

# Colors (Ayu Dark)

# Default colors
[colors.primary]
background = '#0A0E14'
foreground = '#B3B1AD'

# Normal colors
[colors.normal]
black   = '#01060E'
red     = '#EA6C73'
green   = '#91B362'
yellow  = '#F9AF4F'
blue    = '#53BDFA'
magenta = '#FAE994'
cyan    = '#90E1C6'
white   = '#C7C7C7'

# Bright colors
[colors.bright]
black   = '#686868'
red     = '#F07178'
green   = '#C2D94C'
yellow  = '#FFB454'
blue    = '#59C2FF'
magenta = '#FFEE99'
cyan    = '#95E6CB'
white   = '#FFFFFF'

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }

[keyboard]
bindings = [
  { key = "V", mods = "Control", mode = "~Vi", action = "Paste" },
  { key = "Enter", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },
  { key = "0", mods = "Control|Shift", action = "ResetFontSize" },
]
