alias cat='bat --style full'
alias ls='exa --group-directories-first --icons --sort time'
alias ll="${aliases[ls]} -lg"
alias l="${aliases[ll]} -a"
alias ssh='TERM=xterm-256color ssh'
alias tf="terraform"
alias k="kubectl";
alias kb="kubie";
alias kg="kubectl get";
alias kd="kubectl describe";
alias kgp="kubectl get po";
alias kaf="kubectl apply -f";
alias kdf="kubectl delete -f";
alias lg="lazygit";
alias g="git";
alias ga="git add";
alias gb="git branch";
alias gc="git commit";
alias gco="git checkout";
alias gd="git diff";
alias gl="git pull";
alias gp="git push";
alias gst="git status";
alias pbcopy="wl-copy";
alias pbpaste="wl-paste";
alias sw="switch";
