gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
  showFileTree: false
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

services:
  github.tri-ad.tech: 'github:github.tri-ad.tech'

quitOnTopLevelReturn: true
